spring.application.name=cinesmart

# Base de datos MySQL
# Soporta tres entornos tanto mysql, como railway y docker poniendo las variables de entorno
# Conéctate a MySQL en host: localhost, puerto: 3306, base de datos: cinesmart
spring.datasource.url=jdbc:mysql://${MYSQLHOST:${DB_HOST:localhost}}:${MYSQLPORT:3306}/${MYSQLDATABASE:cinesmart}?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
# Usuario de MySQL:
# En railway se usa MYSQLUSER, en docker se usa  DB_USER y 
# En local, si no existe ninguna variable, se usa root
spring.datasource.username=${MYSQLUSER:${DB_USER:root}}
# Contrasena de MySQL:
# En railway se usa MYSQLPASSWORD, en docker se puede usar DB_PASS
# En local si no existe ninguna variable, se usa usuario
spring.datasource.password=${MYSQLPASSWORD:${DB_PASS:usuario}}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Thymeleaf
spring.thymeleaf.cache=false

# Server (Railway inyecta PORT, usamos 8080 por defecto en local)
server.port=${PORT:8080}
